<div class="content-wrapper">
    <?php echo $this->getContent(); ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body">
                        <div class="col-xs-12">
                            <a href="/backend/product/new" class="btn btn-success" style="margin-right: 5px;">
                                <i class="fa fa-credit-card"></i> Thêm mới sản phẩm
                            </a>
                        </div>
                    </div>
                </div>
                <div class="box">
                    <form action="/backend/product/index" method="get" name="frmSearch">
                        <div class="box-header">
                            <div class="col-xs-2">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="keyword"
                                           value="<?php echo $data["keyword"] ?>">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-info">Go!</button>
                                    </span>
                                </div>
                            </div>
                            <div class="col-xs-3">
                                <div class="input-group">
                                <span class="input-group-btn">
                                      <label class="btn btn-info">Danh mục</label>
                                </span>
                                    <select class="form-control" name="categories">
                                        <option value="">Tất cả</option>
                                        <?php showCategories($data["categories"],$data["category"])?>
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-2">
                                <div class="input-group">
                                <span class="input-group-btn">
                                      <label class="btn btn-info">Hiển thị</label>
                                </span>
                                    <select class="form-control" name="limit">
                                        <option value="100" <?php echo 100 == $data["limit"] ? 'selected' : '' ?>>100
                                        </option>
                                        <option value="500" <?php echo 500 == $data["limit"] ? 'selected' : '' ?>>500
                                        </option>
                                        <option value="1000" <?php echo 1000 == $data["limit"] ? 'selected' : '' ?>>
                                            1000
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-2">
                                <div class="input-group">
                                <span class="input-group-btn">
                                      <label class="btn btn-info">Trang</label>
                                </span>
                                    <select class="form-control" name="page">
                                        <?php for ($i = 1; $i <= $data["data"]->last; $i++): ?>
                                            <option
                                                value="<?php echo $i ?>" <?php echo $i == $data["page"] ? 'selected' : '' ?> ><?php echo $i ?></option>
                                        <?php endfor; ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-xs-1">
                                <button class="btn btn-success">Thêm mới</button>
                            </div>
                        </div>
                    </form>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-xs-12">
                                <table id="tableproduct" class="table table-bordered table-striped">
                                    <thead>
                                    <tr>
                                        <th>Sản phẩm</th>
                                        <th>Giá</th>
                                        <th>Sản phẩm Hot</th>
                                        <th>Sản phẩm Mới</th>
                                        <th>Ngày</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($data["data"]->items as $item): ?>
                                        <tr>
                                            <td>
                                                <a href="/backend/product/edit/<?php echo $item->id ?>"><?php echo $item->name; ?></a>
                                            </td>
                                            <td class="product-price" style="text-align:  right">
                                                <?php echo $item->price?>
                                            </td>
                                            <td>
                                                <span
                                                    class="label label-<?php echo $item->is_hot == '1' ? 'success' : 'danger' ?>"><?php echo $item->is_hot == '1' ? 'ON' : 'OFF' ?></span>
                                            </td>
                                            <td>
                                                <span
                                                    class="label label-<?php echo $item->is_new == '1' ? 'success' : 'danger' ?>"><?php echo $item->is_new == '1' ? 'ON' : 'OFF' ?></span>
                                            </td>
                                            <td>
                                                <?php echo date("d-m-Y", strtotime($item->createddate)); ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                    <tfoot>
                                    <tr>
                                    </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>

<script src="/Assets/plugins/jquery.price_format.2.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#tableproduct').dataTable({
            "language": {
                "url": "dataTables.Vietnamese.lang"
            }
        });
        $('.product-price').priceFormat({
            prefix: '', limit: 10, centsLimit: 0,
            thousandsSeparator: ','
        });
    });
</script>

<?php
function showCategories($categories, $id_category_product, $parent_id = 0, $char = '')
{
    foreach ($categories as $key => $item) {
        // Nếu là chuyên mục con thì hiển thị
        if ($item['pid'] == $parent_id) {
            if ($item['id'] == $id_category_product)
                echo '<option value="' . $item['id'] . '" selected >';
            else
                echo '<option value="' . $item['id'] . '">';
            echo $char . $item['name'];
            echo '</option>';

            // Xóa chuyên mục đã lặp
            unset($categories[$key]);

            // Tiếp tục đệ quy để tìm chuyên mục con của chuyên mục đang lặp
            showCategories($categories,$id_category_product ,$item['id'], $char . $item['name'] . ' >>>> ');
        }
    }
}

?>