<div class="cart-box popup">
    <div class="popup-container">
        <div class="cart-entry">
            <a class="image"><img src="/img/theme/product-menu-1.jpg" alt="" /></a>
            <div class="content">
                <a class="title" href="#">Pullover Batwing Sleeve Zigzag</a>
                <div class="quantity">Quantity: 4</div>
                <div class="price">$990,00</div>
            </div>
            <div class="button-x"><i class="fa fa-close"></i></div>
        </div>
        <div class="cart-entry">
            <a class="image"><img src="/img/theme/product-menu-1_.jpg" alt="" /></a>
            <div class="content">
                <a class="title" href="#">Pullover Batwing Sleeve Zigzag</a>
                <div class="quantity">Quantity: 4</div>
                <div class="price">$990,00</div>
            </div>
            <div class="button-x"><i class="fa fa-close"></i></div>
        </div>
        <div class="summary">
            <div class="subtotal">Subtotal: $990,00</div>
            <div class="grandtotal">Grand Total <span>$1029,79</span></div>
        </div>
        <div class="cart-buttons">
            <div class="column">
                <a class="button style-3">view cart</a>
                <div class="clear"></div>
            </div>
            <div class="column">
                <a class="button style-4">checkout</a>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>