<div class="header-wrapper style-1">
    <header class="type-1">
        <div class="header-top">
            <div class="header-top-entry">
                <div class="title"><img src="/img/theme/flag-vietname.jpg" alt="" />English<i class="fa fa-caret-down"></i></div>
                <div class="list">
                    <a href="#" class="list-entry"><img src="/img/theme/flag-lang-2.png" alt="" />French</a>
                    <a href="#" class="list-entry"><img src="/img/theme/flag-lang-3.png" alt="" />Spanish</a>
                </div>
            </div>
            <div class="header-top-entry">
                <div class="title"><b>Currency:</b> $ USD<i class="fa fa-caret-down"></i></div>
                <div class="list">
                    <a href="#" class="list-entry">$ CAD</a>
                    <a href="#" class="list-entry">&#8364; EUR</a>
                </div>
            </div>
            <div class="header-top-entry hidden-xs">
                <div class="title"><i class="fa fa-phone"></i>Any question? Call Us <a href="tel:+987123654"><b>+987 123 654</b></a></div>
            </div>
            <div class="socials-box">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-google-plus"></i></a>
                <a href="#"><i class="fa fa-youtube"></i></a>
                <a href="#"><i class="fa fa-linkedin"></i></a>
                <a href="#"><i class="fa fa-instagram"></i></a>
                <a href="#"><i class="fa fa-pinterest-p"></i></a>
            </div>
            <div class="menu-button responsive-menu-toggle-class"><i class="fa fa-reorder"></i></div>
            <div class="clear"></div>
        </div>

        <div class="header-middle">
            <div class="logo-wrapper">
                <a id="logo" href="#"><img src="/img/theme/logo-2.png" alt="" /></a>
            </div>

            <div class="middle-entry">
                <div class="search-box">
                    <form action="/shop/index" method="get" name="frmSearchProduct">
                        <div class="search-button">
                            <i class="fa fa-search"></i>
                            <input type="submit" />
                        </div>
                        <div class="search-drop-down">
                            <div class="title"><span>All categories</span><i class="fa fa-angle-down"></i></div>
                            <div class="list">
                                <div class="overflow">
                                    <div class="category-entry">Category 1</div>
                                    <div class="category-entry">Category 2</div>
                                    <div class="category-entry">Category 2</div>
                                    <div class="category-entry">Category 4</div>
                                    <div class="category-entry">Category 5</div>
                                    <div class="category-entry">Lorem</div>
                                    <div class="category-entry">Ipsum</div>
                                    <div class="category-entry">Dollor</div>
                                    <div class="category-entry">Sit Amet</div>
                                </div>
                            </div>
                        </div>
                        <div class="search-field">
                            <input type="text" value="" name="keywordproduct" placeholder="Search for product" />
                        </div>
                    </form>
                </div>
            </div>

            <div class="right-entries">
                <a class="header-functionality-entry open-search-popup" href="#"><i class="fa fa-search"></i><span>Search</span></a>
                <a class="header-functionality-entry" href="#"><i class="fa fa-copy"></i><span>Compare</span></a>
                <a class="header-functionality-entry" href="#"><i class="fa fa-heart-o"></i><span>Wishlist</span></a>
                <a class="header-functionality-entry open-cart-popup" href="#"><i class="fa fa-shopping-cart"></i><span>My Cart</span> <b>$255,99</b></a>
            </div>

        </div>

        <div class="close-header-layer"></div>
        <?php $this->partial("share/navigation"); ?>

    </header>
    <div class="clear"></div>
</div>