<div class="breadcrumb-box">
    <a href="#">Home</a>
    <a href="#">Bags &amp; Accessories</a>
</div>

<div class="information-blocks">
    <div class="row">
        <div class="col-md-9 col-md-push-3 col-sm-8 col-sm-push-4">
            <div class="page-selector">
                <div class="pages-box hidden-xs">
                    <a href="#" class="square-button active">1</a>
                    <a href="#" class="square-button">2</a>
                    <a href="#" class="square-button">3</a>
                    <div class="divider">...</div>
                    <a href="#" class="square-button"><i class="fa fa-angle-right"></i></a>
                </div>
                <div class="shop-grid-controls">
                    <div class="entry">
                        <div class="inline-text">Sorty by</div>
                        <div class="simple-drop-down">
                            <select>
                                <option>Position</option>
                                <option>Price</option>
                                <option>Category</option>
                                <option>Rating</option>
                                <option>Color</option>
                            </select>
                        </div>
                        <div class="sort-button"></div>
                    </div>
                    <div class="entry">
                        <div class="view-button active grid"><i class="fa fa-th"></i></div>
                        <div class="view-button list"><i class="fa fa-list"></i></div>
                    </div>
                    <div class="entry">
                        <div class="inline-text">Show</div>
                        <div class="simple-drop-down" style="width: 75px;">
                            <select>
                                <option>12</option>
                                <option>20</option>
                                <option>30</option>
                                <option>40</option>
                            </select>
                        </div>
                        <div class="inline-text">per page</div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="row shop-grid grid-view">

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-1.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="product-image-label type-2"><span>new</span></div>
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-2.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-3.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-4.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-5.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-6.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-7.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-8.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-9.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-10.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-1.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

                <div class="col-md-3 col-sm-4 shop-grid-item">
                    <div class="product-slide-entry shift-image">
                        <div class="product-image">
                            <img src="/img/theme/product-minimal-2.jpg" alt="" />
                            <img src="/img/theme/product-minimal-11.jpg" alt="" />
                            <div class="bottom-line left-attached">
                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                <a class="bottom-line-a square"><i class="fa fa-expand"></i></a>
                            </div>
                        </div>
                        <a class="tag" href="#">Men clothing</a>
                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                        <div class="rating-box">
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="star"><i class="fa fa-star"></i></div>
                            <div class="reviews-number">25 reviews</div>
                        </div>
                        <div class="article-container style-1">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                        <div class="list-buttons">
                            <a class="button style-10">Add to cart</a>
                            <a class="button style-11"><i class="fa fa-heart"></i> Add to Wishlist</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>

            </div>
            <div class="page-selector">
                <div class="description">Showing: 1-3 of 16</div>
                <div class="pages-box">
                    <a href="#" class="square-button active">1</a>
                    <a href="#" class="square-button">2</a>
                    <a href="#" class="square-button">3</a>
                    <div class="divider">...</div>
                    <a href="#" class="square-button"><i class="fa fa-angle-right"></i></a>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <!--Category-->
        <?php $this->partial("share/category"); ?>
    </div>
</div>

<div class="information-blocks">
    <div class="row">
        <div class="col-sm-4 information-entry">
            <h3 class="block-title inline-product-column-title">Featured products</h3>
            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-1.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-2.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-3.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="col-sm-4 information-entry">
            <h3 class="block-title inline-product-column-title">Featured products</h3>
            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-1.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-2.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-3.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <div class="col-sm-4 information-entry">
            <h3 class="block-title inline-product-column-title">Featured products</h3>
            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-1.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-2.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>

            <div class="inline-product-entry">
                <a href="#" class="image"><img alt="" src="/img/theme/product-image-inline-3.jpg"></a>
                <div class="content">
                    <div class="cell-view">
                        <a href="#" class="title">Ladies Pullover Batwing Sleeve Zigzag</a>
                        <div class="price">
                            <div class="prev">$199,99</div>
                            <div class="current">$119,99</div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
