<div class="content-wrapper">
    <?php echo $this->getContent(); ?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Blank page
            <small>it all starts here</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Examples</a></li>
            <li class="active">Blank page</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <p><?php echo $this->flash->output() ?></p>
        <!-- Default box -->
        <div class="row">

            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Title</h3>
                    </div>
                    <form action="/backend/index/saveconfig" method="post" name="webconfig">
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Title SEO</label>
                                <input type="text" class="form-control" id="title" name="title" maxlength="64"
                                       value="<?php echo $data->title ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Description SEO</label>
                                <input type="text" class="form-control" id="description" name="description"
                                       maxlength="128" value="<?php echo $data->meta ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Tên CTY</label>
                                <input type="text" class="form-control" id="companyname" name="companyname"
                                       maxlength="128" value="<?php echo $data->companyname ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Địa chỉ</label>
                                <input type="text" class="form-control" id="address" name="address"
                                       maxlength="256" value="<?php echo $data->address ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Điện thoại</label>
                                <input type="text" class="form-control" id="cellphone" name="cellphone"
                                       maxlength="24" value="<?php echo $data->cellphone ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Email</label>
                                <input type="email" class="form-control" id="email" name="email"
                                       maxlength="24" value="<?php echo $data->email ?>">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Link Facebook</label>
                                <input type="text" class="form-control" id="facebook" name="facebook"
                                       maxlength="256" value="<?php echo $data->facebook ?>">
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Lưu</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- /.box -->
    </section>
    <!-- /.content -->
</div>