<div class="information-blocks">
    <div class="mozaic-banners-wrapper">
        <div class="row">
            <div class="banner-column col-md-6">

                <div class="mozaic-swiper">
                    <div class="swiper-container" data-autoplay="0" data-loop="1" data-speed="500" data-center="0" data-slides-per-view="1">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="mozaic-banner-entry type-1" style="background-image: url(/img/theme/mozaic-banner-1_1.jpg);">
                                    <div class="mozaic-banner-content">
                                        <h3 class="subtitle">Vegetables</h3>
                                        <h2 class="title">Big Sales</h2>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur elit, sed do eiusmod tempor.</div>
                                        <a class="button style-2" href="#">shop now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="mozaic-banner-entry type-1" style="background-image: url(/img/theme/mozaic-banner-1_2.jpg);">
                                    <div class="mozaic-banner-content">
                                        <h3 class="subtitle">French fries</h3>
                                        <h2 class="title">Big Sales</h2>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur elit, sed do eiusmod tempor.</div>
                                        <a class="button style-2" href="#">shop now</a>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="mozaic-banner-entry type-1" style="background-image: url(/img/theme/mozaic-banner-1_3.jpg);">
                                    <div class="mozaic-banner-content">
                                        <h3 class="subtitle">Egzocit Fruits</h3>
                                        <h2 class="title">Big Sales</h2>
                                        <div class="description">Lorem ipsum dolor sit amet, consectetur elit, sed do eiusmod tempor.</div>
                                        <a class="button style-2" href="#">shop now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pagination"></div>
                    </div>
                </div>
            </div>
            <div class="banner-column col-md-3 col-sm-6">
                <div class="mozaic-banner-entry type-1" style="background-image: url(/img/theme/mozaic-banner-2.jpg);">
                    <div class="mozaic-banner-content">
                        <h3 class="subtitle">Nutts from</h3>
                        <h2 class="title">$19,99</h2>
                        <div class="description">Lorem ipsum dolor sit amet, elit, sed do eiusmod.</div>
                        <a class="button style-2" href="#">shop now</a>
                    </div>
                </div>
            </div>
            <div class="banner-column col-md-3 col-sm-6">
                <div class="mozaic-banner-entry type-1" style="background-image: url(/img/theme/mozaic-banner-3.jpg);">
                    <div class="mozaic-banner-content">
                        <h3 class="subtitle">Meat from</h3>
                        <h2 class="title">$12,59</h2>
                        <div class="description">Lorem ipsum dolor sit amet, elit, sed do eiusmod.</div>
                        <a class="button style-2" href="#">shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="information-blocks">
    <div class="tabs-container">
        <div class="swiper-tabs tabs-switch">
            <div class="title">Products</div>
            <div class="list">
                <a class="block-title tab-switcher active">Featured Products</a>
                <a class="block-title tab-switcher">Popular Products</a>
                <a class="block-title tab-switcher">New Arrivals</a>
                <div class="clear"></div>
            </div>
        </div>
        <div>
            <div class="tabs-entry">
                <div class="products-swiper">
                    <div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-1.jpg" alt="" />
                                            <a class="top-line-a left"><i class="fa fa-retweet"></i></a>
                                            <a class="top-line-a right"><i class="fa fa-heart"></i></a>
                                            <div class="bottom-line">
                                                <a class="bottom-line-a"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-2.jpg" alt="" />
                                            <a class="top-line-a right open-product"><i class="fa fa-expand"></i> <span>Quick View</span></a>
                                            <div class="bottom-line">
                                                <div class="right-align">
                                                    <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                    <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                </div>
                                                <div class="left-align">
                                                    <a class="bottom-line-a"><i class="fa fa-shopping-cart"></i> Add to cart</a>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-3.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-4.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-5.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-1.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pagination"></div>
                    </div>
                </div>
            </div>
            <div class="tabs-entry">
                <div class="products-swiper">
                    <div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-1.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-2.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-3.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-4.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-5.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-1.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-2.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-3.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-4.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pagination"></div>
                    </div>
                </div>
            </div>
            <div class="tabs-entry">
                <div class="products-swiper">
                    <div class="swiper-container" data-autoplay="0" data-loop="0" data-speed="500" data-center="0" data-slides-per-view="responsive" data-xs-slides="2" data-int-slides="2" data-sm-slides="3" data-md-slides="4" data-lg-slides="5" data-add-slides="5">
                        <div class="swiper-wrapper">
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-1.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-2.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-3.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-4.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-3.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="swiper-slide">
                                <div class="paddings-container">
                                    <div class="product-slide-entry">
                                        <div class="product-image">
                                            <img src="/img/theme/product-food-2.jpg" alt="" />
                                            <div class="bottom-line left-attached">
                                                <a class="bottom-line-a square"><i class="fa fa-shopping-cart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-heart"></i></a>
                                                <a class="bottom-line-a square"><i class="fa fa-retweet"></i></a>
                                                <a class="bottom-line-a square open-product"><i class="fa fa-expand"></i></a>
                                            </div>
                                        </div>
                                        <a class="tag" href="#">Men clothing</a>
                                        <a class="title" href="#">Blue Pullover Batwing Sleeve Zigzag</a>
                                        <div class="rating-box">
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                            <div class="star"><i class="fa fa-star"></i></div>
                                        </div>
                                        <div class="price">
                                            <div class="prev">$199,99</div>
                                            <div class="current">$119,99</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="pagination"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

