<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Blank Page</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="/Assets/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/Assets/plugins/select2/select2.min.css">
    <link rel="stylesheet" href="/Assets/plugins/datatables/dataTables.bootstrap.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/Assets/dist/css/AdminLTE.min.css">


    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->

    <link rel="stylesheet" href="/Assets/dist/css/skins/_all-skins.min.css">
    <!-- jQuery 2.2.3 -->
    <script src="/Assets/plugins/jQuery/jquery-2.2.3.min.js"></script>
    <!-- Bootstrap 3.3.6 -->
    <script src="/Assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="/Assets/plugins/jquery.validate.min.js"></script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <?php $this->partial("share/main-header"); ?>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <?php $this->partial("share/main-sidebar"); ?>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <?php echo $this->getContent(); ?>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.3.5
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights
        reserved.
    </footer>

    <!-- Control Sidebar -->
    <?php $this->partial("share/control-sidebar"); ?>
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->



<!-- SlimScroll -->
<script src="/Assets/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="/Assets/plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="/Assets/dist/js/app.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="/Assets/dist/js/demo.js"></script>
<script src="/Assets/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/Assets/plugins/datatables/dataTables.bootstrap.min.js"></script>
</body>
</html>